//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.18 at 08:18:54 PM CET 
//


package com.ericsson.oss.mediation.pm.netconf.classes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.ericsson.oss.mediation.pm.netconf.classes.pm.MeasurementReader;
import com.ericsson.oss.mediation.pm.netconf.classes.pm.MeasurementSpecification;
import com.ericsson.oss.mediation.pm.netconf.classes.pm.Pm;
import com.ericsson.oss.mediation.pm.netconf.classes.pm.PmJob;
import com.ericsson.oss.mediation.pm.netconf.classes.top.ManagedElement;
import com.ericsson.oss.mediation.pm.netconf.classes.top.SystemFunctions;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.oss.mediation.pm.netconf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GranularityPeriod_QNAME = new QName("", "granularityPeriod");
    private final static QName _JobType_QNAME = new QName("", "jobType");
    private final static QName _RequestedJobState_QNAME = new QName("", "requestedJobState");
    private final static QName _PmJobId_QNAME = new QName("", "pmJobId");
    private final static QName _ManagedElementId_QNAME = new QName("", "managedElementId");
    private final static QName _ReportingPeriod_QNAME = new QName("", "reportingPeriod");
    private final static QName _GroupRef_QNAME = new QName("", "groupRef");
    private final static QName _MeasurementReaderId_QNAME = new QName("", "measurementReaderId");
    private final static QName _SystemFunctionsId_QNAME = new QName("", "systemFunctionsId");
    private final static QName _PmId_QNAME = new QName("", "pmId");
    private final static QName _JobPriority_QNAME = new QName("", "jobPriority");
    private final static QName _MeasurementTypeRef_QNAME = new QName("", "measurementTypeRef");

    /**
     * Create an instance of {@link ManagedElement }
     * 
     */
    public ManagedElement createManagedElement() {
        return new ManagedElement();
    }

    /**
     * Create an instance of {@link SystemFunctions }
     * 
     */
    public SystemFunctions createSystemFunctions() {
        return new SystemFunctions();
    }

    /**
     * Create an instance of {@link Pm }
     * 
     */
    public Pm createPm() {
        return new Pm();
    }

    /**
     * Create an instance of {@link PmJob }
     * 
     */
    public PmJob createPmJob() {
        return new PmJob();
    }

    /**
     * Create an instance of {@link MeasurementReader }
     * 
     */
    public MeasurementReader createMeasurementReader() {
        return new MeasurementReader();
    }

    /**
     * Create an instance of {@link MeasurementSpecification }
     * 
     */
    public MeasurementSpecification createMeasurementSpecification() {
        return new MeasurementSpecification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "granularityPeriod")
    public JAXBElement<String> createGranularityPeriod(final String value) {
        return new JAXBElement<String>(_GranularityPeriod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jobType")
    public JAXBElement<String> createJobType(final String value) {
        return new JAXBElement<String>(_JobType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "requestedJobState")
    public JAXBElement<String> createRequestedJobState(final String value) {
        return new JAXBElement<String>(_RequestedJobState_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pmJobId")
    public JAXBElement<String> createPmJobId(final String value) {
        return new JAXBElement<String>(_PmJobId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "managedElementId")
    public JAXBElement<String> createManagedElementId(final String value) {
        return new JAXBElement<String>(_ManagedElementId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reportingPeriod")
    public JAXBElement<String> createReportingPeriod(final String value) {
        return new JAXBElement<String>(_ReportingPeriod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "groupRef")
    public JAXBElement<String> createGroupRef(final String value) {
        return new JAXBElement<String>(_GroupRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "measurementReaderId")
    public JAXBElement<String> createMeasurementReaderId(final String value) {
        return new JAXBElement<String>(_MeasurementReaderId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "systemFunctionsId")
    public JAXBElement<String> createSystemFunctionsId(final String value) {
        return new JAXBElement<String>(_SystemFunctionsId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pmId")
    public JAXBElement<String> createPmId(final String value) {
        return new JAXBElement<String>(_PmId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jobPriority")
    public JAXBElement<String> createJobPriority(final String value) {
        return new JAXBElement<String>(_JobPriority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "measurementTypeRef")
    public JAXBElement<String> createMeasurementTypeRef(final String value) {
        return new JAXBElement<String>(_MeasurementTypeRef_QNAME, String.class, null, value);
    }

}
