//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.18 at 08:18:54 PM CET 
//


package com.ericsson.oss.mediation.pm.netconf.classes.pm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}groupRef"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}measurementTypeRef"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="struct" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupRef",
    "measurementTypeRef"
})
@XmlRootElement(name = "measurementSpecification")
public class MeasurementSpecification {

    protected String groupRef;
    protected String measurementTypeRef;
    @XmlAttribute(name = "struct", required = true)
    protected String struct;

    /**
     * Gets the value of the groupRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupRef() {
        return groupRef;
    }

    /**
     * Sets the value of the groupRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupRef(final String value) {
        this.groupRef = value;
    }

    /**
     * Gets the value of the measurementTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementTypeRef() {
        return measurementTypeRef;
    }

    /**
     * Sets the value of the measurementTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementTypeRef(final String value) {
        this.measurementTypeRef = value;
    }

    /**
     * Gets the value of the struct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStruct() {
        return struct;
    }

    /**
     * Sets the value of the struct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStruct(final String value) {
        this.struct = value;
    }

}
