//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.18 at 08:18:54 PM CET 
//


package com.ericsson.oss.mediation.pm.netconf.classes.pm;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}measurementReaderId"/>
 *         &lt;element ref="{}measurementSpecification"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "measurementReaderId",
    "measurementSpecification"
})
@XmlRootElement(name = "MeasurementReader")
public class MeasurementReader {

    @XmlElement(required = true)
    protected String measurementReaderId;
    @XmlElement
    protected MeasurementSpecification measurementSpecification;
    @XmlAttribute(name = "operation", namespace = "urn:ietf:params:xml:ns:netconf:base:1.0")
    protected String operation;

    /**
     * Gets the value of the measurementReaderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementReaderId() {
        return measurementReaderId;
    }

    /**
     * Sets the value of the measurementReaderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementReaderId(final String value) {
        this.measurementReaderId = value;
    }

    /**
     * Gets the value of the measurementSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementSpecification }
     *     
     */
    public MeasurementSpecification getMeasurementSpecification() {
        return measurementSpecification;
    }

    /**
     * Sets the value of the measurementSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementSpecification }
     *     
     */
    public void setMeasurementSpecification(final MeasurementSpecification value) {
        this.measurementSpecification = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(final String value) {
        this.operation = value;
    }

}
