//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.18 at 08:18:54 PM CET 
//


package com.ericsson.oss.mediation.pm.netconf.classes.pm;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}pmId"/>
 *         &lt;element ref="{}PmJob"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pmId",
    "pmJob"
})
@XmlRootElement(name = "Pm")
public class Pm {

    @XmlElement(required = true)
    protected String pmId;
    @XmlElement(name = "PmJob")
    protected PmJob pmJob;

    /**
     * Gets the value of the pmId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmId() {
        return pmId;
    }

    /**
     * Sets the value of the pmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmId(final String value) {
        this.pmId = value;
    }

    /**
     * Gets the value of the pmJob property.
     * 
     * @return
     *     possible object is
     *     {@link PmJob }
     *     
     */
    public PmJob getPmJob() {
        return pmJob;
    }

    /**
     * Sets the value of the pmJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmJob }
     *     
     */
    public void setPmJob(final PmJob value) {
        this.pmJob = value;
    }

}
