//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.18 at 08:18:54 PM CET 
//

package com.ericsson.oss.mediation.pm.netconf.classes.pm;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}pmJobId"/>
 *         &lt;element ref="{}requestedJobState"/>
 *         &lt;element ref="{}reportingPeriod"/>
 *         &lt;element ref="{}jobType"/>
 *         &lt;element ref="{}jobPriority"/>
 *         &lt;element ref="{}granularityPeriod"/>
 *         &lt;element ref="{}MeasurementReader" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "pmJobId", "requestedJobState",
		"reportingPeriod", "jobType", "jobPriority", "granularityPeriod",
		"currentJobState", "jobControl", "compressionType", "jobGroup",
		"measurementReader" })
@XmlRootElement(name = "PmJob")
public class PmJob {

	@XmlElement(required = true)
	protected String pmJobId;
	@XmlElement
	protected String requestedJobState;
	@XmlElement
	protected String reportingPeriod;
	@XmlElement
	protected String jobType;
	@XmlElement
	protected String jobPriority;
	@XmlElement
	protected String granularityPeriod;
	@XmlElement
	protected String currentJobState;
	@XmlElement
	protected String jobControl;
	@XmlElement
	protected String compressionType;
	@XmlElement
	protected String jobGroup;
	@XmlElement(name = "MeasurementReader")
	protected List<MeasurementReader> measurementReader;
	@XmlAttribute(name = "operation", namespace = "urn:ietf:params:xml:ns:netconf:base:1.0")
	protected String operation;

	/**
	 * Gets the value of the pmJobId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPmJobId() {
		return pmJobId;
	}

	/**
	 * Sets the value of the pmJobId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPmJobId(final String value) {
		this.pmJobId = value;
	}

	/**
	 * Gets the value of the requestedJobState property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRequestedJobState() {
		return requestedJobState;
	}

	/**
	 * Sets the value of the requestedJobState property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRequestedJobState(final String value) {
		this.requestedJobState = value;
	}

	/**
	 * Gets the value of the reportingPeriod property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReportingPeriod() {
		return reportingPeriod;
	}

	/**
	 * Sets the value of the reportingPeriod property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReportingPeriod(final String value) {
		this.reportingPeriod = value;
	}

	/**
	 * Gets the value of the jobType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getJobType() {
		return jobType;
	}

	/**
	 * Sets the value of the jobType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setJobType(final String value) {
		this.jobType = value;
	}

	/**
	 * Gets the value of the jobPriority property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getJobPriority() {
		return jobPriority;
	}

	/**
	 * Sets the value of the jobPriority property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setJobPriority(final String value) {
		this.jobPriority = value;
	}

	/**
	 * Gets the value of the granularityPeriod property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGranularityPeriod() {
		return granularityPeriod;
	}

	/**
	 * Sets the value of the granularityPeriod property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGranularityPeriod(final String value) {
		this.granularityPeriod = value;
	}

	/**
	 * Gets the value of the currentJobState property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCurrentJobState() {
		return currentJobState;
	}

	/**
	 * Gets the value of the jobControl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getJobControl() {
		return jobControl;
	}

	/**
	 * Gets the value of the compressionType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompressionType() {
		return compressionType;
	}

	/**
	 * Sets the value of the compressionType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompressionType(final String value) {
		this.compressionType = value;
	}

	/**
	 * Gets the value of the jobGroup property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getJobGroup() {
		return jobGroup;
	}

	/**
	 * Sets the value of the jobGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setJobGroup(final String value) {
		this.jobGroup = value;
	}

	/**
	 * Gets the value of the measurementReader property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the measurementReader property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMeasurementReader().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link MeasurementReader }
	 * 
	 * 
	 */
	public List<MeasurementReader> getMeasurementReader() {
		if (measurementReader == null) {
			measurementReader = new ArrayList<MeasurementReader>();
		}
		return this.measurementReader;
	}

	/**
	 * Gets the value of the operation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOperation() {
		return operation;
	}

	/**
	 * Sets the value of the operation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOperation(final String value) {
		this.operation = value;
	}

}
