//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.18 at 08:18:54 PM CET 
//


package com.ericsson.oss.mediation.pm.netconf.classes.top;

import javax.xml.bind.annotation.*;

import com.ericsson.oss.mediation.pm.netconf.classes.pm.Pm;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}systemFunctionsId"/>
 *         &lt;element ref="{}Pm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systemFunctionsId",
    "pm"
})
@XmlRootElement(name = "SystemFunctions")
public class SystemFunctions {

    @XmlElement(required = true)
    protected String systemFunctionsId;
    @XmlElement(name = "Pm", namespace = "urn:com:ericsson:ecim:SgsnMmePM")
    protected Pm pm;

    /**
     * Gets the value of the systemFunctionsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemFunctionsId() {
        return systemFunctionsId;
    }

    /**
     * Sets the value of the systemFunctionsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemFunctionsId(final String value) {
        this.systemFunctionsId = value;
    }

    /**
     * Gets the value of the pm property.
     * 
     * @return
     *     possible object is
     *     {@link Pm }
     *     
     */
    public Pm getPm() {
        return pm;
    }

    /**
     * Sets the value of the pm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pm }
     *     
     */
    public void setPm(final Pm value) {
        this.pm = value;
    }

}
